config/routes.rb
Rails.application.routes.draw do
  resources :newspapers

  resources :professions

  resources :adverts
  resources :advert_works

  resources :housings

  resources :news_items

  devise_for :users

  resources :trud_govs

  get "home_newspapers" => 'home#newspapers'

  get "static/download1"
  get "static/download2"
  get "static/download3"
  get "static/download4"
  get "static/download5"
  get "static/download6"
  get "static/download7"
  get "static/download10"
  get "static/download9"
  get "static/download8"
  get 'home/map'

  get 'report/amount_places'

  get 'report/amount_by_type'

  get 'report/amount_of_job'

  get 'static/zd'

  get 'static/dms'

  get 'static/centers'

  get 'static/documents'

  get 'static/rs'

  get 'static/sz'

  resources :houses

  get 'home/search'

  get 'api/get_koatuu'
  get 'api/get_areas'

  get 'api/get_regions'

  get 'api/get_koatuu_geo'

  get 'api/get_professions'

  get 'centers/index'

  root to: 'home#index'

  match "*path", :to => "application#render_404", via: [:get]

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :set_housing

  def index
    @area = Koatuu.areas_to_json.collect { |area| [ area[:name], area[:id] ] }
    @house = House.all.collect { |i| [ i.name, i.id.to_s ] }

    respond_to do |format|
      format.js { render :index }
      format.html
    end
  end

  def map
  end

  def newspapers
    @newspapers = Newspaper.all.order(:created_at => :desc)
  end

  private
  def set_housing
    params[:home_search_region] ||= ''
    params[:home_search_area] ||= ''
    params[:home_search_rubric] ||= ''
    koatuu = params[:home_search_region].slice(0,5)
    koatuu = params[:home_search_area].slice(0,2) if koatuu.empty?

    scool = params[:home_search_has_school]
    has_kgarden = params[:home_search_has_kgarden]

    @housings = Housing.where('qty_places > 0')
    @housings = @housings.where("koatuu_code like ?", "#{koatuu}%") unless koatuu.empty?
    @housings = @housings.where(:has_school => 1) unless scool.nil?
    @housings = @housings.where(:has_kgarden => 1) unless has_kgarden.nil?

    @housings = @housings.order('koatuu_code').paginate(:page => params[:page]) if @housings

    @adverts = Advert.where('qty_places > 0')
    @adverts = @adverts.where("koatuu_code like ?", "#{koatuu}%") unless koatuu.empty?
    @adverts = @adverts.where(:has_school => 1) unless scool.nil?
    @adverts = @adverts.where(:has_kgarden => 1) unless has_kgarden.nil?
    @adverts = @adverts.where("datetime(created_at) >= ?",  Date.current - 3.months)

    @adverts = @adverts.order(created_at: :desc).paginate(:page => params[:adverts_page]) if @adverts


    @advert_works = AdvertWork.all
    @advert_works = @advert_works.includes(:advert).references(:advert).where("adverts.koatuu_code like ?", "#{koatuu}%") unless koatuu.empty?
    @advert_works = @advert_works.includes(:profession).references(:profession).where("professions.id" => params[:home_search_rubric]) unless params[:home_search_rubric].empty?
    @advert_works = @advert_works.where("datetime(:created_at) >= ?",  Date.current - 3.months)

    @advert_works = @advert_works.order(created_at: :desc).paginate(:page => params[:advert_works_page]) if @advert_works
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_no_results.html.erb
<div style="margin: 15px 0;" class="alert alert-info"><%= t("home.results.empty") %></div>

app/views/home/_results.html.erb
<table class="table table-striped">
<thead>
<tr>
  <th><%= t('.area') %></th>
  <th><%= t('.house') %></th>
  <% if places.first.respond_to?(:cost) %>
      <th><small><%= t('.cost').html_safe %></small></th>
  <% else %>
      <th><small><%= t('.places').html_safe %></small></th>
  <% end %>
  <th><small><%= t('.school') %> /<br> <%= t('.kgarten') %></small></th>
</tr>
</thead>
<tbody>
<% places.each do |housing| %>
<% coatuu = Koatuu.coatuu_to_json(housing.koatuu_code) %>
<% if coatuu %>
    <% work = work_class(housing.koatuu_code) %>
    <tr>
      <td>
        <%= "#{coatuu[:area]}" %>
        <br>
        <%= "#{coatuu[:name] || coatuu[:region]}" %>
      </td>
      <td><%= housing.house.name %></td>
      <td>

        <a href="<%= static_centers_path %>#tel_0510100000"><%= housing.qty_places %></a>
        <!--<a target="_blank" href="<%= work[:url] %>"><%= work[:places] %></a>-->

      </td>
      <%- school = school_class(housing.has_school) %>
      <%- garden = kgarten_class(housing.has_kgarden) %>
      <td ><i style="padding-left: 5px; color: <%= school[:color] %>" class="<%= school[:class] %>"></i> <i style="padding-left: 15px; color: <%= garden[:color] %>" class="<%= garden[:class] %>"></i></td>
      <td>
       </td>
    </tr>
    <% end %>
<% end %>
</tbody>
</table>

<div class="flickr_pagination ">
  <%= paginate places, :container => false %>
</div>

app/views/home/_results_advert.html.erb
<table class="table table-striped">
<thead>
<tr>
  <th><%= t('.area') %></th>
  <th><%= t('.house') %></th>
  <th><small><%= t('.places').html_safe %></small></th>
  <th><small><%= t('.school') %> /<br> <%= t('.kgarten') %></small></th>
</tr>
</thead>
<tbody>
<% places.each do |housing| %>
<% coatuu = Koatuu.coatuu_to_json(housing.koatuu_code) %>
<% if coatuu %>
    <% work = work_class(housing.koatuu_code) %>
    <tr>
      <td>
        <%= "#{coatuu[:area]}" %>
        <br>
        <%= "#{coatuu[:name] || coatuu[:region]}" %>
        <% if housing.respond_to?(:address) %>
          <br>
          <%= housing[:address] %>
        <% end %>
      </td>
      <td><%= housing.house.name %>
        <br/>
        <small>тел. <%= housing.phone %></small>
      </td>
      <td>

        <a href="<%= static_centers_path %>#tel_0510100000"><%= housing.qty_places %></a> /
        <%= housing[:cost] %>
      </td>
      <%- school = school_class(housing.has_school) %>
      <%- garden = kgarten_class(housing.has_kgarden) %>
      <td ><i style="padding-left: 5px; color: <%= school[:color] %>" class="<%= school[:class] %>"></i> <i style="padding-left: 15px; color: <%= garden[:color] %>" class="<%= garden[:class] %>"></i></td>
      <td>
       </td>
    </tr>
    <% end %>
<% end %>
</tbody>
</table>

<div class="flickr_pagination ">
  <%= paginate(places, :param_name => 'adverts_page') %>
</div>

app/views/home/_results_advert_work.html.erb
<table class="table table-striped">
<thead>
<tr>
  <th><%= t('adverts.index.koatuu_code') %></th>
  <th><%= t('advert_works.form.profession') %></th>
  <th><small><%= t('advert_works.form.places').html_safe %> / <br/><%= t('advert_works.form.salary').html_safe %></small></th>
</tr>
</thead>
<tbody>
<% places.each do |housing| %>
<% coatuu = Koatuu.coatuu_to_json(housing.advert[:koatuu_code]) %>
<% if coatuu %>
    <% work = work_class(housing.advert[:koatuu_code]) %>
    <tr>
      <td>
        <%= "#{coatuu[:area]}" %>
        <br>
        <%= "#{coatuu[:name] || coatuu[:region]}" %>
      </td>
      <td><%= housing.profession.name %>
      </td>
      <td>
        <a href="<%= static_centers_path %>#tel_0510100000"><%= housing.places %></a> /
        <%= housing[:salary] %>
      </td>
    </tr>
    <% end %>
<% end %>
</tbody>
</table>

<div class="flickr_pagination ">
  <%= paginate(places, :param_name => 'advert_works_page') %>
</div>

app/views/home/_uk_map.html.erb
<div class="uk_map"></div>

    <div id="map" class="col-sm-12"></div>


<script src="assets/raphael-min.js"></script>


<script type="text/javascript">
    $(document).ready(function () {
        function get_html_for_ev(area) {
            return "<div id='map_tooltip'><h5>" + area.name + "</h5><hr/><p>для проживання: <b>" + area.qtt + "</b></p><p>вакансій: <b>" + area.qtt_work + "</b></p></div>"
        }

        $.getJSON("<%= api_get_koatuu_geo_path %>", function( data ) {
            var div = d3.select(".uk_map").append("div")
                    .attr("class", "map_tooltip")
                    .style("opacity", 0);


            var color = d3.scale.linear()
                    .range(['rgb(240,249,232)','rgb(123,204,196)','rgb(67,162,202)','rgb(8,104,172)'])
            color.domain([
                0, d3.max(data, function(d) { return d.qtt})
            ])


            size = $('#map').width()
            $('#map').css('margin-left', -50)

            var r = Raphael('map', 700, 400),
                    attributes = {
                        stroke: '#5A8FA5',
                        'stroke-width': 2,
                        'stroke-linejoin': 'round',
                        transform:"translate(623.5801,201.2119)",
                        transform:"matrix(1.25,0,0,-1.25,0,950)"
                    },
                    arr = r.set();
            for (var region in uk_map_paths) {
                var obj = r.path(uk_map_paths[region].path);

                obj.attr(attributes);

                var area_data = $.grep(data, function(e){ return e.code == uk_map_paths[region].code; })[0];

                if (area_data === undefined) {
                    area_data = {code: uk_map_paths[region].code, area: "", name: uk_map_paths[region].name, qtt: 0, qtt_work: 0 }
                    obj.data('area', area_data )
                    obj.attr('fill', '#fff')
                } else {
                    obj.data('area', area_data )
                    obj.attr('fill', color(area_data.qtt + area_data.qtt_work))
                }

                obj.data('fill', obj.attr('fill'))

                obj
                    .attr('cursor', 'pointer')
                    .hover(function(event){
                            div.html( get_html_for_ev(this.data('area')) )
                                    .style("left", event.offsetX-100 + "px")
                                    .style("top", event.offsetY + 100 + "px");

                            div.transition()
                                .duration(200)
                                .style("opacity", .9)
                                .style("color", '#fff')
                        this.animate({
                            fill: '#F0D06A'
                        }, 100);
                    }, function(){
                            div.transition()
                                    .duration(200)
                                    .style("opacity", 0);

                            if (this.data('area').area != '' && $("#home_search_area").select2("val") == this.data('area').area) {
                                var _this = this
                                $('form.search').submit(function() {
                                    if ($("#home_search_area").select2("val") != _this.data('area').area) {
                                        _this.animate({
                                            fill: _this.data('fill')
                                        }, 200);
                                    }
                                })
                                return
                            }

                            this.animate({
                                fill: this.data('fill')
                            }, 200);
                    })
                    .click(function(){
                            area = this.data('area')

                            $("#home_search_area").select2("val", '' + area.area)
                            $("#home_search_region").select2("val", '')

                            $('form.search').submit()
                    });



                arr.push(obj);
            }

            arr.transform("s0.5,0.45 0,0");
        })

    });
</script>

app/views/home/_work.html.erb
<%= text_field_tag 'home_search_rubric', params[:home_search_rubric], { 'placeholder' => t('home.search.work_placeholder'), :class => 'form-control col-lg-10' } %>


<script type="text/javascript">
    $(document).ready(function() {
        $("#home_search_rubric").select2({
            allowClear:true,
            ajax: {
                url: "/api/get_professions",
                dataType: 'json',
                data: function (term, page) {
                    return {
                        q: term, // search term
                        page_limit: 10,
                    };
                },
                results: function (data, page) { // parse the results into the format expected by Select2.
                    // since we are using custom formatting functions we do not need to alter remote JSON data
                    return {results: data, text: "name" };
                }
            },
            formatSelection: function(item) {
                return item.name
            },
            formatResult: function(item) {
                return item.name
            }
        });
    });
</script>

app/views/home/index.html.erb
<% content_for :sub_menu do %>
    <div class="search-heading">
      <div class="col-md-4 active">
        <i class="fa fa-home"></i> <%= t('home.menu.search') %>
      </div>
      <div class="col-md-4">
        <a class="" href="<%= home_map_path %>"><i class="fa fa-map-marker"></i> <%= t('home.menu.search_map') %></a>
      </div>
    </div>

    <div class="btn-group pull-right" style="margin-right: 20px;">
      <%= link_to t('home.menu.advert'), adverts_path, :class => "btn btn-success" %>
      <button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown">
        <span class="caret"></span>
        <span class="sr-only">Toggle Dropdown</span>
      </button>
      <ul class="dropdown-menu" role="menu">
          <li>
            <%= link_to new_advert_path, "data-no-turbolink" => true, :role => "menuitem" do %>
                <%= t('home.menu.add_houseadvert') %>
            <% end %>
          </li>
          <li>
            <%= link_to new_advert_work_path, "data-no-turbolink" => true, :role => "menuitem" do %>
                <%= t('home.menu.add_jobadvert') %>
            <% end %>
          </li>
      </ul>
    </div>

<% end %>
<div class="panel-heading">
  <h1><%= t("home.menu.search") %></h1>
</div>
<div class="search-container">

  <%= form_tag(root_path, method: "get", remote: true, class: 'search' ) do %>

      <div class="btn-group btn-group-justified">
        <div class="btn-group">
          <%= render partial: 'search_area' %>
        </div>
        <div class="btn-group">
          <%= render partial: 'search_region' %>
        </div>
        <div class="btn-group">
            <%= render partial: 'work' %>
        </div>
      </div>

      <br>

      <div class="btn-group btn-group-justified">
        <div class="btn-group">
        </div>
        <div class="btn-group">
          <label><%= check_box_tag('home_search_has_school') %> <%= t('home.search.school') %></label>
        </div>
        <div class="btn-group">
          <label><%= check_box_tag('home_search_has_kgarden') %> <%= t('home.search.kgarten') %></label>
        </div>
        <div class="btn-group">
          <!--<button class="btn btn-primary" ><i class="fa fa-search"> <%= t('home.search.search')%></i></button>-->
        </div>
      </div>

  <% end %>

  <div class="row">
    <%= render partial: 'uk_map' %>
  </div>


  <div id="spinner"></div>

  <!-- Nav tabs -->
  <ul class="nav nav-tabs" role="tablist">
    <li class="active"><a href="#res_housings" role="tab" data-toggle="tab"><%= t('.housings') %></a></li>
    <li><a href="#res_adverts" role="tab" data-toggle="tab"><%= t('.adverts') %></a></li>
    <li><a href="#res_advert_works" role="tab" data-toggle="tab"><%= t('.adverts_work') %></a></li>
  </ul>

  <div class="tab-content">
    <div class="tab-pane fade in active" id="res_housings">
      <div id="tbl_housings">
          <%= render partial: 'results', :locals => { :places => @housings } %>
      </div>
    </div>
    <div class="tab-pane fade" id="res_adverts">
      <div id="tbl_adverts">
        <%= render partial: 'results_advert', :locals => { :places => @adverts } %>
      </div>
    </div>
    <div class="tab-pane fade" id="res_advert_works">
      <div id="tbl_advert_works">
        <%= render partial: 'results_advert_work', :locals => { :places => @advert_works } %>
      </div>
    </div>
  </div>
  <p class="note"><%= %></p>
</div>


<script id="script_home_search_area" type="text/javascript">
    $('input, select', 'form.search').on("change", function(e) {
        $('#spinner').addClass('spinner')
        if ($("#home_search_area").select2("val") == '')
            $("#home_search_region").select2("val", "")

        $('form.search').submit()
    });
</script>

app/views/home/index.js.erb
<% if @housings && @housings.count > 0 %>
    $("#tbl_housings").html("<%= escape_javascript(render partial: 'results', :locals => { :places => @housings }) %>");
<% else %>
    $("#tbl_housings").html("<%= escape_javascript(render partial: 'no_results') %>");
<% end %>


<% if @adverts && @adverts.count > 0 %>
    $("#tbl_adverts").html("<%= escape_javascript(render partial: 'results_advert', :locals => { :places => @adverts }) %>");
<% else %>
    $("#tbl_adverts").html("<%= escape_javascript(render partial: 'no_results') %>");
<% end %>

<% if @advert_works && @advert_works.count > 0 %>
    $("#tbl_advert_works").html("<%= escape_javascript(render partial: 'results_advert_work', :locals => { :places => @advert_works }) %>");
<% else %>
    $("#tbl_advert_works").html("<%= escape_javascript(render partial: 'no_results') %>");
<% end %>


$("#spinner").removeClass('spinner').fadeIn(100);

app/views/home/map.html.erb
<% content_for :title, t("home.menu.search_map") %>
<% content_for :sub_menu do %>
    <div class="search-heading">
      <div class="col-md-4 active">
        <i class="fa fa-map-marker"></i> <%= t('home.menu.search_map') %>
      </div>
      <div class="col-md-4">
        <a class="" href="<%= root_path %>"><i class="fa fa-home"></i> <%= t('home.menu.search') %></a>
      </div>
    </div>
<% end %>
<div class="panel-heading">
  <h1><%= t("home.menu.search_map") %></h1>
</div>
<div class="search-container row">

  <div id="mapdiv" class="row" style=" height:600px;">
    <div class="spinner"></div>
  </div>
</div>

<script type="text/javascript">

    function get_regions(code, alon, alat, azoom) {
        console.log(code)
        $.getJSON("<%= api_get_koatuu_geo_path %>", { area: code }, function( data ) {
            /* Создание маркеров области */
            CreateMarkers(LayerRayon, data);

            SetMapCenterZoom(alon, alat, azoom)
        });
    }

    $(document).ready(function () {
        $('#mapdiv').html('');

        window.geo = {}
        window.map = {}
        window.epsg4326 = {}
        window.projectTo = {};

        StartInitMap("mapdiv");
        SetGeoPositionStandart();

        window.LayerOblast=new OpenLayers.Layer.Vector("Overlay");
        window.LayerRayon=new OpenLayers.Layer.Vector("Overlay");

        SetMapCenterZoom(3530470.0647431, 6243369.337484, 6);

        /* Контроллер для показа маркеров областей */
        window.controls = {
            selectorArea: new OpenLayers.Control.SelectFeature(LayerOblast, {onSelect: createPopup, onUnselect: destroyPopup}),
            selectorRegion: new OpenLayers.Control.SelectFeature(LayerRayon, {onSelect: createPopup, onUnselect: destroyPopup})
        };
        map.addControl(controls['selectorArea']);
        map.addControl(controls['selectorRegion']);
        controls['selectorArea'].activate();
        controls['selectorRegion'].activate();



        map.events.register("zoomend", map, function(e) { EventAfterZoom(e.object.zoom); });
        map.events.register("moveend", map, function(e) { Wcenter=e.object.center ; lat=Wcenter.lat; lon=Wcenter.lon;
            LimitTop=6863120.762734;LimitBottom=5504681.8962389 ;LimitLeft=2440783.7896614;LimitRight=4601811.453039;
            if (lon < LimitLeft  ||  lon > LimitRight  ||  lat > LimitTop  ||  lat < LimitBottom ){SetMapCenterZoom(3530470.0647431, 6243369.337484, 6);}
        });



        $.getJSON("<%= api_get_koatuu_geo_path %>", function( data ) {
            /* Создание маркеров области */
            CreateMarkers(LayerOblast, data);
        });

    })

</script>

app/views/home/newspapers.html.erb
<% content_for :title, t("layouts.newspapers") %>
<% @newspapers.each do |newspaper| %>
    <div class="col-xs-10 col-xs-offset-1">
        <%= newspaper.embed.html_safe %>
    </div>
<% end %>

app/views/home/search.js.erb
$("#results").hide()
<% if @housings && @housings.count > 0 %>
    $("#results").html("<%= escape_javascript(render partial: 'results') %>");
<% else %>
    $("#results").html("<%= escape_javascript(render partial: 'no_results') %>");
<% end %>

$("#results").fadeIn(100);