config/routes.rb
Rails.application.routes.draw do
  resources :newspapers

  resources :professions

  resources :adverts
  resources :advert_works

  resources :housings

  resources :news_items

  devise_for :users

  resources :trud_govs

  get "home_newspapers" => 'home#newspapers'

  get "static/download1"
  get "static/download2"
  get "static/download3"
  get "static/download4"
  get "static/download5"
  get "static/download6"
  get "static/download7"
  get "static/download10"
  get "static/download9"
  get "static/download8"
  get 'home/map'

  get 'report/amount_places'

  get 'report/amount_by_type'

  get 'report/amount_of_job'

  get 'static/zd'

  get 'static/dms'

  get 'static/centers'

  get 'static/documents'

  get 'static/rs'

  get 'static/sz'

  resources :houses

  get 'home/search'

  get 'api/get_koatuu'
  get 'api/get_areas'

  get 'api/get_regions'

  get 'api/get_koatuu_geo'

  get 'api/get_professions'

  get 'centers/index'

  root to: 'home#index'

  match "*path", :to => "application#render_404", via: [:get]

end

app/models/advert.rb
class Advert < ActiveRecord::Base
  belongs_to :housing
  belongs_to :house

  has_one :advert_work, dependent: :destroy

  scope :users_adverts, lambda { |email| where(email: email).order(:created_at => :desc)}

  validates_presence_of  :qty_places, :message => I18n.t('errors.messages.empty')
  validates_presence_of  :phone, :message => I18n.t('errors.messages.empty')


  def self.group_qtt code
    where("koatuu_code like ?", "#{code}%").sum('qty_places')
  end

end

app/controllers/adverts_controller.rb
class AdvertsController < ApplicationController
  before_filter :authenticate_user!
  load_and_authorize_resource

  before_action :set_advert, only: [:show, :edit, :update, :destroy]

  before_action :set_cookies, only: [:create, :update]

  # GET /adverts
  # GET /adverts.json
  def index
    if current_user.has_role? :editor
      @adverts = Advert.order(:created_at => :desc)
    else
      @adverts = Advert.users_adverts(current_user.email)
    end

    @adverts = @adverts.paginate(:page => params[:page], :per_page => 10)
  end

  # GET /adverts/1
  # GET /adverts/1.json
  def show
  end

  # GET /adverts/new
  def new
    @advert = Advert.new({:email => current_user.email, :fio => cookies['user_fio'], :phone => cookies['user_phone']})
  end

  # GET /adverts/1/edit
  def edit
  end

  # POST /adverts
  # POST /adverts.json
  def create

    @advert = Advert.new(advert_params)
    #if !verify_recaptcha
      respond_to do |format|
        if @advert.save
          format.html { redirect_to @advert, notice: t('adverts.form.created') }
        else
          format.html { render :new }
        end
      end
    #else
    #  #binding.pry
    #  respond_to do |format|
    #    format.html { render :new, notice: 'невірний CAPTCHA код.' }
    #    format.js { render json: { notice: 'невірний CAPTCHA код.' }, status: :unprocessable_entity }
    #  end
    #end
  end

  # PATCH/PUT /adverts/1
  # PATCH/PUT /adverts/1.json
  def update
    respond_to do |format|
      if @advert.update(advert_params)
        format.html { redirect_to @advert, notice: t('adverts.form.updated') }
        format.json { render :show, status: :ok, location: @advert }
      else
        format.html { render :edit }
        format.json { render json: @advert.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /adverts/1
  # DELETE /adverts/1.json
  def destroy
    @advert.destroy
    respond_to do |format|
      format.html { redirect_to adverts_url, notice: t('adverts.form.destroyed') }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_advert
      @advert = Advert.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def advert_params
      params.require(:advert).permit(:koatuu_code, :house_id, :address, :cost, :qty_places, :has_school, :has_kgarden, :email, :fio, :phone, :note)
    end

    def set_cookies
      response.set_cookie('user_fio', advert_params[:fio])
      response.set_cookie('user_phone', advert_params[:phone])
    end

end

app/helpers/adverts_helper.rb
module AdvertsHelper
  def get_koatuu_tree
    koatuu_tree = Rails.cache.read('koatuu_tree')
    if koatuu_tree.nil?
      koatuu_tree = Koatuu.to_tree
      Rails.cache.write('koatuu_tree', koatuu_tree, timeToLive: (30 * 60).seconds)
    end
    koatuu_tree
  end
end

app/views/adverts/_form.html.erb
<% if @advert.errors.any? %>
    <div class="alert-dismissible">
      <div class="alert alert-danger" role="alert">
        <h3><%= t('.error_title')%></h3>
        <ul class="">
            <% @advert.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
        </ul>
      </div>
    </div>
<% end %>

<%= form_for @advert, :html => { :class => 'form-horizontal' } do |f| %>

    <div id="wizard" class="swMain">
      <ul>
        <li><a href="#step-1">
          <label class="stepNumber">1</label>
                <span class="stepDesc">
                   <%= t('.step')%> 1<br />
                   <small><%= t('.place')%></small>
                </span>
        </a></li>
        <li><a href="#step-2">
          <label class="stepNumber">2</label>
                <span class="stepDesc">
                   <%= t('.step')%> 2<br />
                   <small><%= t('.contact')%></small>
                </span>
        </a></li>
        <li><a href="#step-3">
          <label class="stepNumber">3</label>
                <span class="stepDesc">
                   <%= t('.step')%> 3<br />
                   <small><%= t('.publish')%></small>
                </span>
        </a></li>
      </ul>

      <div id="step-1">
        <h2 class="StepTitle"><%= t('housings.index.koatuu') %></h2>
        <br/>
        <div class="form-group">
          <div class="controls">
            <%= f.select :koatuu_code, grouped_options_for_select(get_koatuu_tree(), @advert.koatuu_code), { prompt: false },  :class => 'form-control' %>
          </div>
        </div>
        <div class="form-group">
          <%= f.label t('housings.index.house'), :class => 'control-label' %>
          <div class="controls">
            <%= f.select :house_id, House.all.collect {|p| [ p.name, p.id ] }, { prompt: false }, :class => 'form-control' %>
          </div>
        </div>
        <br/>
        <div class="form-group">
          <div class="input-group">
            <div class="input-group-addon"><i class="fa fa-home"></i></div>
            <%= f.text_field :address, :class => 'form-control', placeholder: t('.addr_placeholder') %>
          </div>
        </div>

        <div class="form-group">
          <label for="inputEmail3" class="col-sm-8 control-label"><b><%= t('.qtt_places')%></b></label>
          <div class="controls col-sm-4">
            <%= f.text_field :qty_places, :class => 'form-control', placeholder: t('.qtt_placeholder') %>
          </div>
        </div>
        <div class="form-group">
          <label for="inputEmail3" class="col-sm-8 control-label"><%= t('.cost')%></label>
          <div class="controls  col-sm-4">
            <%= f.text_field :cost, :class => 'form-control', placeholder: t('.cost_placeholder') %>
          </div>
        </div>
        <h2 class="StepTitle"><%= t('.motes') %></h2>
        <br/>
        <div class="btn-group btn-group-justified">
          <div class="btn-group form-group">
            <label class="col-lg-5"><%= f.check_box :has_school %> <%= t('.hasschool') %></label>
            <label class="col-lg-5"><%= f.check_box :has_kgarden %> <%= t('.haskgarten') %></label>
          </div>
        </div>
      </div>

      <div id="step-2">
        <h2 class="StepTitle"><%= t('.contact_step') %></h2>
        <div class="form-group">
          <label for="inputEmail3" class="control-label">E-Mail</label>
          <div class="input-group">
            <div class="input-group-addon"><i class="fa fa-envelope-o"></i></div>
            <%= f.text_field :email, :class => 'form-control', :readonly => true, placeholder: "example@example.com" %>
          </div>
        </div>
        <div class="form-group">
          <label for="inputEmail3" class="control-label"><%= t('.fio') %></label>
          <div class="input-group">
            <div class="input-group-addon"><i class="fa fa-user-md"></i></div>
            <%= f.text_field :fio, :class => 'form-control', placeholder: t('.fio_placeholder') %>
          </div>
        </div>
        <div class="form-group">
          <label for="inputEmail3" class="control-label"><b><%= t('.phone') %></b></label>
          <div class="input-group">
            <div class="input-group-addon"><i class="fa fa-mobile"></i></div>
            <%= f.text_field :phone, { :class => 'form-control' } %>
          </div>
        </div>
      </div>

      <div id="step-3">
        <h2 class="StepTitle"><%= t('.notes') %></h2>
        <div class="form-group">
          <div class="controls">
            <%= f.text_area :note, {:rows => 10, :class => 'form-control'} %>
          </div>
        </div>

        <!--<h2 class="StepTitle">Для збереження даних введіть код CAPTCHA</h2>-->
        <!--<%= recaptcha_tags ajax: true %>-->
      </div>
    </div>
    <!-- End SmartWizard Content -->

<% end %>


<script type="text/javascript">

    $(document).ready(function() {
        $("form #advert_koatuu_code").select2();
        $("form #advert_house_id").select2();
    });

</script>

<script type="text/javascript">

    $(document).ready(function(){
        // Smart Wizard
        $('form #wizard').smartWizard( {
            enableAllSteps: true,
            labelNext: '<%= t('wizard.next') %>', // label for Next button
            labelPrevious:'<%= t('wizard.back') %>', // label for Previous button
            labelFinish: '<%= t('wizard.finish') %>',
            onFinish: onFinishCallback
        });

        function onFinishCallback(){
            $('form').submit()
        }
    });

</script>

app/views/adverts/edit.html.erb
<% content_for :title, t(".title") %>
<%- model_class = Advert -%>
<div class="page-header">
  <h3><%= t('.title')%></h3>
</div>
<%= render :partial => 'form' %>

app/views/adverts/index.html.erb
<% content_for :title, t(".title") %>
<%- model_class = Advert -%>
<div class="page-header">
  <h2><%=t '.title' %></h2>
</div>
<table class="table">
  <th><%= t('.koatuu_code') %></th>
  <th><%= t('.type') %></th>
  <th><%= t('.qty_places') %></th>
  <th><%= t('.cost') %></th>
  <th><%= t('.created') %></th>
  <th><%=t '.actions', :default => t("helpers.actions") %></th>
  <tbody>
    <% @adverts.each do |advert| %>
      <tr>
        <td><%= get_koatuu_name(advert.koatuu_code) %></td>

        <% if advert.advert_work %>
            <td>
              <%= link_to "#{t('.advert_work')}: #{advert.advert_work.profession.name}", advert_work_path(advert.advert_work)%>
            </td>
            <td><%= advert.advert_work.places %></td>
            <td><%= advert.advert_work.salary %></td>
        <% else %>
            <td>
              <%= link_to "#{t('.advert_rent')}: #{advert.house.nil? ? '' : advert.house.name }", advert_path(advert)%>
            </td>
            <td><%= advert.qty_places %></td>
            <td><%= advert.cost %></td>
        <% end %>

        <td><%=l advert.created_at %></td>
        <td>
          <% if advert.advert_work %>
              <%= link_to t('.edit', :default => t("helpers.links.edit")),
                          edit_advert_work_path(advert.advert_work), :class => 'btn btn-default btn-xs' %>
          <% else %>
              <%= link_to t('.edit', :default => t("helpers.links.edit")),
                          edit_advert_path(advert), :class => 'btn btn-default btn-xs' %>
          <% end %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      advert_path(advert),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>

  <% end %>
  </tbody>
</table>


<div class="flickr_pagination ">
  <%= will_paginate @adverts, :container => false %>
</div>


<hr>
<%= link_to t('.new_rent', :default => t("helpers.links.new")),
            new_advert_path,
            :class => 'btn btn-success' %>

<%= link_to t('.new_work', :default => t("helpers.links.new")),
            new_advert_work_path,
            :class => 'btn btn-success' %>

app/views/adverts/new.html.erb
<% content_for :title, t(".title") %>
<%- model_class = Advert -%>
<div class="page-header">
  <h3><%= t('.title')%></h3>
</div>
<%= render :partial => 'form' %>

app/views/adverts/show.html.erb
<%- model_class = Advert -%>
<div class="page-header">
  <h3><%= t('.title')%></h3>
</div>

<dl class="dl-horizontal">
  <div class="col-sm-12">
      <dt><strong><%= t('adverts.index.koatuu_code') %>:</strong></dt>
      <dd><%= get_koatuu_name(@advert.koatuu_code) %></dd>
  </div>
  <div class="col-sm-12">
      <dt><strong><%= t('adverts.index.house_id') %>:</strong></dt>
      <dd><%= @advert.house.name unless @advert.house.nil? %></dd>
  </div>
  <div class="col-sm-12">
      <dt><strong><%= t('adverts.index.address') %>:</strong></dt>
      <dd><%= @advert.address %></dd>
  </div>
  <div class="col-sm-12">
      <dt><strong><%= t('adverts.index.qty_places') %>:</strong></dt>
      <dd><%= @advert.qty_places %></dd>
  </div>
  <div class="col-sm-12">
      <dt><strong><%= t('adverts.index.cost') %>:</strong></dt>
      <dd><%= @advert.cost %></dd>
  </div>
  <div class="col-sm-12">
    <dt><strong><%= t('adverts.index.has_school') %>:</strong></dt>
    <%- school = school_class(@advert.has_school) %>
    <dd><i style="color: <%= school[:color] %>" class="<%= school[:class] %>"></i></dd>
  </div>
  <div class="col-sm-12">
    <dt><strong><%= t('adverts.index.has_kgarden') %>:</strong></dt>
    <%- garten = kgarten_class(@advert.has_kgarden) %>
    <dd><i style="color: <%= garten[:color] %>" class="<%= garten[:class] %>"></i></dd>
  </div>
  <div class="col-sm-12">
      <dt><strong><%= t('adverts.index.email') %>:</strong></dt>
      <dd><%= @advert.email %></dd>
  </div>
  <div class="col-sm-12">
      <dt><strong><%= t('adverts.index.fio') %>:</strong></dt>
      <dd><%= @advert.fio %></dd>
  </div>
  <div class="col-sm-12">
      <dt><strong><%= t('adverts.index.phone') %>:</strong></dt>
      <dd><%= @advert.phone %></dd>
  </div>
  <div class="col-sm-12">
      <dt><strong><%= t('adverts.index.note') %>:</strong></dt>
      <dd><%= @advert.note %></dd>
  </div>
</dl>


<%= link_to t('.back', :default => t("helpers.links.back")),
              adverts_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_advert_path(@advert), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              advert_path(@advert),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>