config/routes.rb
Rails.application.routes.draw do
  resources :newspapers

  resources :professions

  resources :adverts
  resources :advert_works

  resources :housings

  resources :news_items

  devise_for :users

  resources :trud_govs

  get "home_newspapers" => 'home#newspapers'

  get "static/download1"
  get "static/download2"
  get "static/download3"
  get "static/download4"
  get "static/download5"
  get "static/download6"
  get "static/download7"
  get "static/download10"
  get "static/download9"
  get "static/download8"
  get 'home/map'

  get 'report/amount_places'

  get 'report/amount_by_type'

  get 'report/amount_of_job'

  get 'static/zd'

  get 'static/dms'

  get 'static/centers'

  get 'static/documents'

  get 'static/rs'

  get 'static/sz'

  resources :houses

  get 'home/search'

  get 'api/get_koatuu'
  get 'api/get_areas'

  get 'api/get_regions'

  get 'api/get_koatuu_geo'

  get 'api/get_professions'

  get 'centers/index'

  root to: 'home#index'

  match "*path", :to => "application#render_404", via: [:get]

end

app/models/newspaper.rb
class Newspaper < ActiveRecord::Base
end

app/controllers/newspapers_controller.rb
class NewspapersController < ApplicationController
  before_filter :authenticate_user!
  load_and_authorize_resource

  before_action :set_newspaper, only: [:show, :edit, :update, :destroy]

  # GET /newspapers
  # GET /newspapers.json
  def index
    @newspapers = Newspaper.all.order(:created_at => :desc)
  end

  # GET /newspapers/1
  # GET /newspapers/1.json
  def show
  end

  # GET /newspapers/new
  def new
    @newspaper = Newspaper.new
  end

  # GET /newspapers/1/edit
  def edit
  end

  # POST /newspapers
  # POST /newspapers.json
  def create
    @newspaper = Newspaper.new(newspaper_params)

    respond_to do |format|
      if @newspaper.save
        format.html { redirect_to @newspaper, notice: 'Newspaper was successfully created.' }
        format.json { render :show, status: :created, location: @newspaper }
      else
        format.html { render :new }
        format.json { render json: @newspaper.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /newspapers/1
  # PATCH/PUT /newspapers/1.json
  def update
    respond_to do |format|
      if @newspaper.update(newspaper_params)
        format.html { redirect_to @newspaper, notice: 'Newspaper was successfully updated.' }
        format.json { render :show, status: :ok, location: @newspaper }
      else
        format.html { render :edit }
        format.json { render json: @newspaper.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /newspapers/1
  # DELETE /newspapers/1.json
  def destroy
    @newspaper.destroy
    respond_to do |format|
      format.html { redirect_to newspapers_url, notice: 'Newspaper was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_newspaper
      @newspaper = Newspaper.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def newspaper_params
      params.require(:newspaper).permit(:embed)
    end
end

app/helpers/newspapers_helper.rb
module NewspapersHelper
end

app/views/newspapers/_form.html.erb
<%= form_for @newspaper, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="form-group">
    <%= f.label :embed, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :embed, :class => 'form-control' %>
    </div>
  </div>

  
  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            newspapers_path, :class => 'btn btn-default' %>
 
<% end %>

app/views/newspapers/edit.html.erb
<%- model_class = Newspaper -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/newspapers/index.html.erb
<%- model_class = Newspaper -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:embed) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @newspapers.each do |newspaper| %>
      <tr>
        <td><%= link_to newspaper.id, newspaper_path(newspaper) %></td>
        <td><%= newspaper.embed %></td>
        <td><%=l newspaper.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_newspaper_path(newspaper), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      newspaper_path(newspaper),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_newspaper_path,
            :class => 'btn btn-primary' %>

app/views/newspapers/new.html.erb
<%- model_class = Newspaper -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/newspapers/show.html.erb
<%- model_class = Newspaper -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:embed) %>:</strong></dt>
  <dd><%= @newspaper.embed %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              newspapers_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_newspaper_path(@newspaper), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              newspaper_path(@newspaper),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>